name: Serenity Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [aarch64, i686, x86_64]
        toolchain: [GNU, Clang]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: serenity-build
          tags: |
            ghcr.io/fdschonborn/serenity-build:${{matrix.target}}-${{matrix.toolchain}}
