name: Serenity (GNU)

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        target:
          - aarch64
          - i686
          - x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: serenity
          build-args: |
            toolchain=GNU
            target=${{ matrix.target }}
          push: true
          tags: |
            ghcr.io/fdschonborn/serenity:GNU-${{ matrix.target }}
